# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"
      addToPath: true
  - script: |
      sudo apt update
      sudo apt install mysql-server -y
      sudo pat install libmysqlclient-dev -y
    displayName: "Install dependencies, mysql libmysqlclient"

  - script: |
      sudo apt install python3-pip python3-dev python3-setuptools -y
    displayName: "Install dependencies, python3"

  - script: |
      sudo apt install build-essential libssl-dev libffi-dev -y
    displayName: "Install dependencies, other dependencies"

  - script: |
      python -m venv venv
      source venv/bin/activate
    displayName: "Activate environment"

  - script: |
      source venv/bin/activate
      python3 manage.py runserver -h "0.0.0.0" -p 5000
    displayName: "Run server"

  - task: AzureRmWebAppDeployment@4
    condition: succeeded()
    displayName: "Deploy to Azure"